config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users/destroy_confirm' => 'users#destroy_confirm', as: 'user_destroy_confirm'
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: [:index]

  # 開発環境で送信したメールを /letter_opener で確認する
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :book, optional: true
  belongs_to :book_comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.all
    # sleep(5)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="<%= "unchecked" if notification.checked == false %>">
  <%= link_to visitor.name, user_path(visitor) %>さんが
  <% case notification.action %>
  <% when 'follow' then %>
    <%= "あなたをフォローしました" %>
  <% when 'like' then %>
    <%= link_to 'あなたの投稿', notification.book %>
    <%= "にいいねしました" %>
    <p class="text-muted">
      <%= Book.find_by(id: notification.book.id)&.body %>
    </p>
  <% when 'comment' then %>
    <% if notification.book.user_id == visited.id %>
      <%= link_to 'あなたの投稿', notification.book %>
    <% else %>
      <%= link_to "#{notification.book.user.name}さんの投稿" , book_path(notification.book) %>
    <% end %>
    <%= "にコメントしました" %>
    <p class="text-muted">
      <%= BookComment.find_by(id: notification.book_comment.id)&.comment %>
    </p>
  <% end %>
  <div class="small text-muted">
    <%= time_ago_in_words(notification.created_at) %>前
  </div>
</div>

<hr>

app/views/notifications/index.html.erb
<div class="container">
  <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
  <% if notifications.exists? %>
    <%= render notifications %>
  <% else %>
    <p>通知はありません</p>
  <% end %>
</div>